
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


import ByteBuf from '../bright/serialization/ByteBuf'

export namespace Enum { 
export enum EAccessFlag {
    WRITE = 1,
    READ = 2,
    TRUNCATE = 4,
    NEW = 8,
    READ_WRITE = WRITE|READ,
}

} 
export namespace Enum { 
export enum EItemType {
    /**
     * 
     */
    A = 1,
    /**
     * 
     */
    B = 2,
    /**
     * 
     */
    C = 3,
}

} 
export namespace Enum { 
export enum ETestQuality {
    /**
     * 
     */
    A = 1,
    /**
     * 
     */
    B = 2,
    /**
     * 
     */
    C = 3,
    /**
     * 
     */
    D = 4,
}

} 




export namespace DataTable {
export class Item {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Desc = _buf_.ReadString()
        this.Name = _buf_.ReadString()
        this.Icon = _buf_.ReadString()
        this.BundleName = _buf_.ReadString()
        this.Param = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.AddRateType = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.AddRateType.push(_e0);}}
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Desc: string
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly Icon: string
    /**
     * Bundle,resource
     */
    readonly BundleName: string
    /**
     * 
     */
    readonly Param: string
    /**
     * 
     */
    readonly AddRateType: number[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
    }
}

}


export namespace test {
export abstract class Shape {
    static constructorFrom(_buf_: ByteBuf): Shape{
        switch (_buf_.ReadInt()) {
            case 2131829196: return new test.Circle(_buf_)
            case 694982337: return new test2.Rectangle(_buf_)
            default: throw new Error()
        }
    }

    constructor(_buf_: ByteBuf) {
    }


    resolve(tables:Tables) {
    }
}

}


export namespace test {
/**
 * 
 */
export class Circle extends test.Shape {

    constructor(_buf_: ByteBuf) {
        super(_buf_)
        this.radius = _buf_.ReadFloat()
    }

    /**
     * 
     */
    readonly radius: number

    resolve(tables:Tables) {
        super.resolve(tables)
        
    }
}

}


export namespace test2 {
/**
 * 
 */
export class Rectangle extends test.Shape {

    constructor(_buf_: ByteBuf) {
        super(_buf_)
        this.width = _buf_.ReadFloat()
        this.height = _buf_.ReadFloat()
    }

    /**
     * 
     */
    readonly width: number
    /**
     * 
     */
    readonly height: number

    resolve(tables:Tables) {
        super.resolve(tables)
        
        
    }
}

}


export namespace test {
/**
 * excel
 */
export class TestExcelBean1 {

    constructor(_buf_: ByteBuf) {
        this.x1 = _buf_.ReadInt()
        this.x2 = _buf_.ReadString()
        this.x3 = _buf_.ReadInt()
        this.x4 = _buf_.ReadFloat()
    }

    /**
     * 
     */
    readonly x1: number
    /**
     * 
     */
    readonly x2: string
    /**
     * 
     */
    readonly x3: number
    /**
     * 
     */
    readonly x4: number

    resolve(tables:Tables) {
        
        
        
        
    }
}

}


export namespace test {
/**
 * excel
 */
export class TestExcelBean2 {

    constructor(_buf_: ByteBuf) {
        this.y1 = _buf_.ReadInt()
        this.y2 = _buf_.ReadString()
        this.y3 = _buf_.ReadFloat()
    }

    /**
     * 
     */
    readonly y1: number
    /**
     * 
     */
    readonly y2: string
    /**
     * 
     */
    readonly y3: number

    resolve(tables:Tables) {
        
        
        
    }
}

}



export class TrAtlas {

    constructor(_buf_: ByteBuf) {
        this.Key = _buf_.ReadString()
        this.Path = _buf_.ReadString()
        this.BundleName = _buf_.ReadString()
    }

    /**
     * Key
     */
    readonly Key: string
    /**
     * 
     */
    readonly Path: string
    /**
     * bundle
     */
    readonly BundleName: string

    resolve(tables:Tables) {
        
        
        
    }
}





export class TrAudio {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Type = _buf_.ReadInt()
        this.Resource = _buf_.ReadString()
        this.Volume = _buf_.ReadFloat()
        this.Loop = _buf_.ReadBool()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Type: number
    /**
     * 
     */
    readonly Resource: string
    /**
     * 0~1
     */
    readonly Volume: number
    /**
     * 
     */
    readonly Loop: boolean

    resolve(tables:Tables) {
        
        
        
        
        
    }
}





export class TrAVGMap {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Path = _buf_.ReadString()
        this.Name = _buf_.ReadString()
        this.BGM = _buf_.ReadString()
        this.Ambient = _buf_.ReadString()
        this.Isdrag = _buf_.ReadBool()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Bgunlock = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Bgunlock.push(_e0);}}
        this.Text = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ScenegroupId = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.ScenegroupId.push(_e0);}}
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Path: string
    /**
     * 
     */
    readonly Name: string
    /**
     * bgm
     */
    readonly BGM: string
    /**
     * 
     */
    readonly Ambient: string
    /**
     * 
     */
    readonly Isdrag: boolean
    /**
     * 
     */
    readonly Bgunlock: number[]
    /**
     * 
     */
    readonly Text: string
    /**
     * id
     */
    readonly ScenegroupId: number[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
    }
}





export class TrAVGNPC {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.SpineUnlock = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.SpineUnlock.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ChoiceStory = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.ChoiceStory.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ChoiceText = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.ChoiceText.push(_e0);}}
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly SpineUnlock: number[]
    /**
     * AVG
     */
    readonly ChoiceStory: number[]
    /**
     * AVG
     */
    readonly ChoiceText: string[]

    resolve(tables:Tables) {
        
        
        
        
        
    }
}





export class TrAVGScene {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Path = _buf_.ReadString()
        this.Name = _buf_.ReadString()
        this.BGM = _buf_.ReadString()
        this.Ambient = _buf_.ReadString()
        this.Isdrag = _buf_.ReadBool()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Bgunlock = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Bgunlock.push(_e0);}}
        this.Text = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.EventStoryId = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.EventStoryId.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.EventStoryCondition = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.EventStoryCondition.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.storyisrepeat = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadBool(); this.storyisrepeat.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.EventGameId = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.EventGameId.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.EventGameCondition = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.EventGameCondition.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.GameIsRepeat = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadBool(); this.GameIsRepeat.push(_e0);}}
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Path: string
    /**
     * 
     */
    readonly Name: string
    /**
     * bgm
     */
    readonly BGM: string
    /**
     * 
     */
    readonly Ambient: string
    /**
     * 
     */
    readonly Isdrag: boolean
    /**
     * 
     */
    readonly Bgunlock: number[]
    /**
     * 
     */
    readonly Text: string
    /**
     * ID
     */
    readonly EventStoryId: number[]
    /**
     * 
     */
    readonly EventStoryCondition: number[]
    /**
     * 
     */
    readonly storyisrepeat: boolean[]
    /**
     * ID
     */
    readonly EventGameId: number[]
    /**
     * 
     */
    readonly EventGameCondition: number[]
    /**
     * 
     */
    readonly GameIsRepeat: boolean[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrAVGSceneGroup {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Bgunlock = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Bgunlock.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Scenegroup = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Scenegroup.push(_e0);}}
        this.Initialscene = _buf_.ReadInt()
        this.Event = _buf_.ReadInt()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly Bgunlock: number[]
    /**
     * id
     */
    readonly Scenegroup: number[]
    /**
     * id
     */
    readonly Initialscene: number
    /**
     * 
     */
    readonly Event: number

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class TrBook {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.PhoneIcon = _buf_.ReadString()
        this.Name = _buf_.ReadString()
        this.NickName = _buf_.ReadString()
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly PhoneIcon: string
    /**
     * 
     */
    readonly Name: string
    /**
     * ()
     */
    readonly NickName: string

    resolve(tables:Tables) {
        
        
        
        
    }
}





export class TrBoyFriend {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.BriefIntro = _buf_.ReadString()
        this.Icon = _buf_.ReadString()
        this.PhoneIcon = _buf_.ReadString()
        this.Pic = _buf_.ReadString()
        this.HalfPic = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Unlock = new Map<number, number>(); for(let i = 0 ; i < n ; i++) { let _k0; _k0 = _buf_.ReadInt();  let _v0;  _v0 = _buf_.ReadInt(); this.Unlock.set(_k0, _v0);  } }
        this.VideoId = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.FavoriteItem = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.FavoriteItem.push(_e0);}}
        this.FavoriteItemNum = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ConfuseItem = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.ConfuseItem.push(_e0);}}
        this.ConfuseItemNum = _buf_.ReadInt()
        this.FavoriteItemVideo = _buf_.ReadInt()
        this.ConfuseItemVideo = _buf_.ReadInt()
        this.NormalItemVideo = _buf_.ReadString()
        this.Age = _buf_.ReadInt()
        this.Height = _buf_.ReadInt()
        this.Character = _buf_.ReadString()
        this.Favorite = _buf_.ReadString()
        this.Hate = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Intro = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.Intro.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.IntroUnlock = new Map<number, number>(); for(let i = 0 ; i < n ; i++) { let _k0; _k0 = _buf_.ReadInt();  let _v0;  _v0 = _buf_.ReadInt(); this.IntroUnlock.set(_k0, _v0);  } }
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly BriefIntro: string
    /**
     * 
     */
    readonly Icon: string
    /**
     * 
     */
    readonly PhoneIcon: string
    /**
     * 
     */
    readonly Pic: string
    /**
     * 
     */
    readonly HalfPic: string
    /**
     * 
     */
    readonly Unlock: Map<number, number>
    /**
     * id
     */
    readonly VideoId: number
    /**
     * id
     */
    readonly FavoriteItem: number[]
    /**
     * 
     */
    readonly FavoriteItemNum: number
    /**
     * id
     */
    readonly ConfuseItem: number[]
    /**
     * 
     */
    readonly ConfuseItemNum: number
    /**
     * 
     */
    readonly FavoriteItemVideo: number
    /**
     * 
     */
    readonly ConfuseItemVideo: number
    /**
     * 
     */
    readonly NormalItemVideo: string
    /**
     * 
     */
    readonly Age: number
    /**
     * 
     */
    readonly Height: number
    /**
     * 
     */
    readonly Character: string
    /**
     * 
     */
    readonly Favorite: string
    /**
     * 
     */
    readonly Hate: string
    /**
     * 1|2
     */
    readonly Intro: string[]
    /**
     * |,|
     */
    readonly IntroUnlock: Map<number, number>

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrBoyFriendLevel {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Exp = _buf_.ReadInt()
    }

    /**
     * id*1000+
     */
    readonly Id: number
    /**
     * 
     */
    readonly Exp: number

    resolve(tables:Tables) {
        
        
    }
}





export class TrChat {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.PeopleId = _buf_.ReadInt()
        this.GroupId = _buf_.ReadInt()
        this.TargetId = _buf_.ReadInt()
        this.Type = _buf_.ReadInt()
        this.Text = _buf_.ReadString()
        this.Picture = _buf_.ReadString()
        this.BigPicture = _buf_.ReadString()
        this.Video = _buf_.ReadInt()
        this.NextId = _buf_.ReadInt()
        this.IfAnswer = _buf_.ReadBool()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ChoiceTexts = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.ChoiceTexts.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ChoiceNextIds = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.ChoiceNextIds.push(_e0);}}
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly PeopleId: number
    /**
     * id
     */
    readonly GroupId: number
    /**
     * 
     */
    readonly TargetId: number
    /**
     * 
     */
    readonly Type: number
    /**
     * 
     */
    readonly Text: string
    /**
     * 
     */
    readonly Picture: string
    /**
     * 
     */
    readonly BigPicture: string
    /**
     * 
     */
    readonly Video: number
    /**
     * id
     */
    readonly NextId: number
    /**
     * 
     */
    readonly IfAnswer: boolean
    /**
     * ,Textid
     */
    readonly ChoiceTexts: string[]
    /**
     * ID
     */
    readonly ChoiceNextIds: number[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrChoice {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Type = _buf_.ReadInt()
        this.Text1 = _buf_.ReadString()
        this.C1type = _buf_.ReadInt()
        this.Next1Id = _buf_.ReadInt()
        this.Text2 = _buf_.ReadString()
        this.C2type = _buf_.ReadInt()
        this.Next2Id = _buf_.ReadInt()
        this.Text3 = _buf_.ReadString()
        this.C3type = _buf_.ReadInt()
        this.Next3Id = _buf_.ReadInt()
        this.Text4 = _buf_.ReadString()
        this.C4type = _buf_.ReadInt()
        this.Next4Id = _buf_.ReadInt()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     *  
     */
    readonly Type: number
    /**
     * 1
     */
    readonly Text1: string
    /**
     * 1
     */
    readonly C1type: number
    /**
     * 1ID
     */
    readonly Next1Id: number
    /**
     * 2
     */
    readonly Text2: string
    /**
     * 2
     */
    readonly C2type: number
    /**
     * 2ID
     */
    readonly Next2Id: number
    /**
     * 3
     */
    readonly Text3: string
    /**
     * 3
     */
    readonly C3type: number
    /**
     * 3ID
     */
    readonly Next3Id: number
    /**
     * 4
     */
    readonly Text4: string
    /**
     * 4
     */
    readonly C4type: number
    /**
     * 4ID
     */
    readonly Next4Id: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrCondition {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.ConditionType = _buf_.ReadInt()
        this.MatchingType = _buf_.ReadInt()
        this.Param1 = _buf_.ReadInt()
        this.Param2 = _buf_.ReadInt()
        this.Value1 = _buf_.ReadInt()
        this.Value2 = _buf_.ReadInt()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly ConditionType: number
    /**
     * 
     */
    readonly MatchingType: number
    /**
     * 
     */
    readonly Param1: number
    /**
     * 
     */
    readonly Param2: number
    /**
     * 1
     */
    readonly Value1: number
    /**
     * 2
     */
    readonly Value2: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
    }
}





export class TrConst {

    constructor(_buf_: ByteBuf) {
        this.Key = _buf_.ReadString()
        this.Int = _buf_.ReadInt()
        this.Float = _buf_.ReadFloat()
    }

    /**
     * Key
     */
    readonly Key: string
    readonly Int: number
    readonly Float: number

    resolve(tables:Tables) {
        
        
        
    }
}





export class TrDate {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.RoleId = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.DateType = _buf_.ReadInt()
        this.DateTypeName = _buf_.ReadString()
        this.UnlockLevel = _buf_.ReadInt()
        this.PlotId = _buf_.ReadInt()
        this.Pic = _buf_.ReadString()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * id
     */
    readonly RoleId: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly DateType: number
    /**
     * 
     */
    readonly DateTypeName: string
    /**
     * 
     */
    readonly UnlockLevel: number
    /**
     * id
     */
    readonly PlotId: number
    /**
     * 
     */
    readonly Pic: string

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
    }
}





export class TrEffect {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Path = _buf_.ReadString()
    }

    /**
     * int
     */
    readonly Id: number
    /**
     * 
     */
    readonly Path: string

    resolve(tables:Tables) {
        
        
    }
}





export class TrGuide {

    constructor(_buf_: ByteBuf) {
        this.GuideID = _buf_.ReadInt()
        this.Type = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Condition = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Condition.push(_e0);}}
        this.Parm1 = _buf_.ReadString()
        this.Parm2 = _buf_.ReadString()
        this.Parm3 = _buf_.ReadString()
    }

    /**
     * Id
     */
    readonly GuideID: number
    /**
     * 
     */
    readonly Type: number
    /**
     * ID
     */
    readonly Condition: number[]
    /**
     * 1
     */
    readonly Parm1: string
    /**
     * 2
     */
    readonly Parm2: string
    /**
     * 3
     */
    readonly Parm3: string

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class TrHeroinePropType {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Icon = _buf_.ReadString()
        this.Name = _buf_.ReadString()
        this.ValueType = _buf_.ReadInt()
    }

    /**
     * 
     */
    readonly Id: number
    /**
     * 
     */
    readonly Icon: string
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly ValueType: number

    resolve(tables:Tables) {
        
        
        
        
    }
}





export class TrIdentity {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Actor = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.Bg = _buf_.ReadString()
        this.Icon = _buf_.ReadString()
        this.TendProp = _buf_.ReadInt()
        this.Desc = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.TxtSubliming = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.TxtSubliming.push(_e0);}}
        this.SublimingLevel = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Feature1 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.Feature1.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Feature2 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.Feature2.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Feature3 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.Feature3.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Feature4 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.Feature4.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Feature5 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.Feature5.push(_e0);}}
    }

    /**
     * ID
     */
    readonly Id: number
    /**
     * ID
     */
    readonly Actor: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly Bg: string
    /**
     * 
     */
    readonly Icon: string
    /**
     * ID
     */
    readonly TendProp: number
    /**
     * 
     */
    readonly Desc: string
    /**
     * 
     */
    readonly TxtSubliming: string[]
    /**
     * 
     */
    readonly SublimingLevel: number
    /**
     * 1
     */
    readonly Feature1: string[]
    /**
     * 2
     */
    readonly Feature2: string[]
    /**
     * 3
     */
    readonly Feature3: string[]
    /**
     * 4
     */
    readonly Feature4: string[]
    /**
     * 5
     */
    readonly Feature5: string[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrIdentityLevel {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.IdentityId = _buf_.ReadInt()
        this.Level = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.NeedItem = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.NeedItem.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.NeedCurrency = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.NeedCurrency.push(_e0);}}
        this.Prop1 = _buf_.ReadInt()
        this.Prop2 = _buf_.ReadInt()
        this.Prop3 = _buf_.ReadInt()
        this.Prop4 = _buf_.ReadInt()
        this.Prop5 = _buf_.ReadInt()
    }

    /**
     * ID
     */
    readonly Id: number
    /**
     * id
     */
    readonly IdentityId: number
    /**
     * 
     */
    readonly Level: number
    /**
     * 
     */
    readonly NeedItem: number[]
    /**
     * 
     */
    readonly NeedCurrency: number[]
    /**
     * id1
     */
    readonly Prop1: number
    /**
     * id2
     */
    readonly Prop2: number
    /**
     * id3
     */
    readonly Prop3: number
    /**
     * id4
     */
    readonly Prop4: number
    /**
     * id5
     */
    readonly Prop5: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrInteraction {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Desc = _buf_.ReadString()
        this.Cost = _buf_.ReadInt()
        this.Exp = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.Icon = _buf_.ReadString()
        this.UnlockLv = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.VideoIdList = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.VideoIdList.push(_e0);}}
        this.Openfunction = _buf_.ReadInt()
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Desc: string
    /**
     * 
     */
    readonly Cost: number
    /**
     * 
     */
    readonly Exp: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly Icon: string
    /**
     * 
     */
    readonly UnlockLv: number
    /**
     * id
     */
    readonly VideoIdList: number[]
    /**
     * 
     */
    readonly Openfunction: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
    }
}





export class TrLevel {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.NeedExp = _buf_.ReadInt()
        this.PowAdd = _buf_.ReadInt()
        this.MagicKey = _buf_.ReadInt()
        this.MagicKeyMax = _buf_.ReadInt()
        this.MagicBoxReward = _buf_.ReadInt()
    }

    /**
     * 
     */
    readonly Id: number
    /**
     * 
     */
    readonly NeedExp: number
    /**
     * 
     */
    readonly PowAdd: number
    /**
     * 
     */
    readonly MagicKey: number
    /**
     * 
     */
    readonly MagicKeyMax: number
    /**
     * (%)
     */
    readonly MagicBoxReward: number

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class TrMagicBoxRandom {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.MagicBoxType = _buf_.ReadInt()
        this.StrText = _buf_.ReadString()
        this.UIId = _buf_.ReadInt()
        this.StoryId = _buf_.ReadInt()
        this.Equal = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Award1 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Award1.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Award2 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Award2.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Award3 = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Award3.push(_e0);}}
        this.TriggerTime = _buf_.ReadInt()
        this.Weight = _buf_.ReadInt()
        this.ConditionType = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ConditionId = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.ConditionId.push(_e0);}}
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly MagicBoxType: number
    /**
     * 
     */
    readonly StrText: string
    /**
     * UIID
     */
    readonly UIId: number
    /**
     * ID
     */
    readonly StoryId: number
    /**
     * 
     */
    readonly Equal: number
    /**
     * 1
     */
    readonly Award1: number[]
    /**
     * 2
     */
    readonly Award2: number[]
    /**
     * 3
     */
    readonly Award3: number[]
    /**
     * 
     */
    readonly TriggerTime: number
    /**
     * 
     */
    readonly Weight: number
    /**
     * 
     */
    readonly ConditionType: number
    /**
     * 
     */
    readonly ConditionId: number[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrOpenFunction {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.OpenFunctionType = _buf_.ReadInt()
        this.IfShowUI = _buf_.ReadBool()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ConditionId = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.ConditionId.push(_e0);}}
        this.UnConditionType = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.Desc = _buf_.ReadString()
        this.Icon = _buf_.ReadString()
        this.RedType = _buf_.ReadInt()
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly OpenFunctionType: number
    /**
     * 
     */
    readonly IfShowUI: boolean
    /**
     * 
     */
    readonly ConditionId: number[]
    /**
     * 
     */
    readonly UnConditionType: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly Desc: string
    /**
     * 
     */
    readonly Icon: string
    /**
     * 
     */
    readonly RedType: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
    }
}





export class TrPlayer {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.IconPath = _buf_.ReadString()
        this.Name = _buf_.ReadString()
        this.Prop1 = _buf_.ReadInt()
        this.Prop2 = _buf_.ReadInt()
        this.Prop3 = _buf_.ReadInt()
        this.Prop4 = _buf_.ReadInt()
        this.Prop5 = _buf_.ReadInt()
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly IconPath: string
    /**
     * 
     */
    readonly Name: string
    /**
     * id1
     */
    readonly Prop1: number
    /**
     * id2
     */
    readonly Prop2: number
    /**
     * id3
     */
    readonly Prop3: number
    /**
     * id4
     */
    readonly Prop4: number
    /**
     * id5
     */
    readonly Prop5: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
    }
}





export class TrPlot {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.ElementType = _buf_.ReadInt()
        this.ElementName = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ElementList = []; for(let i = 0 ; i < n ; i++) { let _e0; { let n = Math.min(_buf_.ReadSize(), _buf_.Size); _e0 = []; for(let i = 0 ; i < n ; i++) { let _e1; _e1 = _buf_.ReadInt(); _e0.push(_e1);}}; this.ElementList.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.AwardType = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.AwardType.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.AwardValue = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.AwardValue.push(_e0);}}
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly ElementType: number
    /**
     * 
     */
    readonly ElementName: string
    /**
     * 
     */
    readonly ElementList: number[][]
    /**
     * 
     */
    readonly AwardType: number[]
    /**
     * 
     */
    readonly AwardValue: number[]

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class TrPropValue {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.PropTypeId = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.PropValue = _buf_.ReadInt()
        this.ValueType = _buf_.ReadInt()
    }

    /**
     * ID
     */
    readonly Id: number
    /**
     * ID
     */
    readonly PropTypeId: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly PropValue: number
    /**
     * 
     */
    readonly ValueType: number

    resolve(tables:Tables) {
        
        
        
        
        
    }
}





export class Trreloading {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Desc = _buf_.ReadString()
        this.Open = _buf_.ReadInt()
        this.AD = _buf_.ReadInt()
        this.IconId = _buf_.ReadString()
        this.InterId = _buf_.ReadInt()
        this.InterId1 = _buf_.ReadInt()
        this.InterId2 = _buf_.ReadInt()
        this.InterId3 = _buf_.ReadInt()
        this.InterId4 = _buf_.ReadInt()
        this.InterId5 = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.InteractionVideo = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.InteractionVideo.push(_e0);}}
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Desc: string
    /**
     * 
     */
    readonly Open: number
    /**
     * 
     */
    readonly AD: number
    /**
     * 
     */
    readonly IconId: string
    /**
     * id
     */
    readonly InterId: number
    /**
     * 
     */
    readonly InterId1: number
    /**
     * 
     */
    readonly InterId2: number
    /**
     * 
     */
    readonly InterId3: number
    /**
     * 
     */
    readonly InterId4: number
    /**
     * 
     */
    readonly InterId5: number
    /**
     * id
     */
    readonly InteractionVideo: number[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrShopGift {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.ItemId = _buf_.ReadInt()
    }

    /**
     * Id
     */
    readonly Id: number
    readonly ItemId: number

    resolve(tables:Tables) {
        
        
    }
}





export class TrSpecialEvent {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.NpcId = _buf_.ReadInt()
        this.BuildId = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.FirstEventId = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.FirstEventId.push(_e0);}}
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * NpcId
     */
    readonly NpcId: number
    /**
     * Id
     */
    readonly BuildId: number
    /**
     * id
     */
    readonly FirstEventId: number[]

    resolve(tables:Tables) {
        
        
        
        
    }
}





export class TrStrDictionary {

    constructor(_buf_: ByteBuf) {
        this.Key = _buf_.ReadString()
        this.Zh = _buf_.ReadString()
        this.English = _buf_.ReadString()
    }

    /**
     * Key
     */
    readonly Key: string
    /**
     * 
     */
    readonly Zh: string
    readonly English: string

    resolve(tables:Tables) {
        
        
        
    }
}





export class TrTalk {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.NextId = _buf_.ReadInt()
        this.GroupId = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.IsOwner = _buf_.ReadBool()
        this.ContentKey = _buf_.ReadString()
        this.BgPathKey = _buf_.ReadString()
        this.MeSpinePath = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.MeSpineAnimGroup = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.MeSpineAnimGroup.push(_e0);}}
        this.SpinePath = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.SpineOffset = new Map<string, number>(); for(let i = 0 ; i < n ; i++) { let _k0; _k0 = _buf_.ReadString();  let _v0;  _v0 = _buf_.ReadFloat(); this.SpineOffset.set(_k0, _v0);  } }
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.SpineAnimGroup = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.SpineAnimGroup.push(_e0);}}
        this.AudioId = _buf_.ReadInt()
        this.SoundId = _buf_.ReadInt()
        this.AmbientSoundId = _buf_.ReadInt()
        this.BGM = _buf_.ReadInt()
        this.EffectId = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Pos = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.Pos.push(_e0);}}
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * id-1
     */
    readonly NextId: number
    /**
     * ID
     */
    readonly GroupId: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly IsOwner: boolean
    /**
     * 
     */
    readonly ContentKey: string
    /**
     * 
     */
    readonly BgPathKey: string
    /**
     * spine
     */
    readonly MeSpinePath: string
    /**
     * spine
     */
    readonly MeSpineAnimGroup: string[]
    /**
     * NPCspine
     */
    readonly SpinePath: string
    /**
     * NPCspinex|0,y|0
     */
    readonly SpineOffset: Map<string, number>
    /**
     * NPCspine
     */
    readonly SpineAnimGroup: string[]
    /**
     *  id
     */
    readonly AudioId: number
    /**
     *  id
     */
    readonly SoundId: number
    /**
     * id
     */
    readonly AmbientSoundId: number
    /**
     * id
     */
    readonly BGM: number
    /**
     * id
     */
    readonly EffectId: number
    /**
     * 
     */
    readonly Pos: string[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrTask {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.TaskOrder = _buf_.ReadInt()
        this.TaskType = _buf_.ReadInt()
        this.Text = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.TaskCondition = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.TaskCondition.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.EndCondition = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.EndCondition.push(_e0);}}
        this.AwardGroup = _buf_.ReadInt()
        this.AwardNum = _buf_.ReadInt()
        this.Jump = _buf_.ReadString()
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly TaskOrder: number
    /**
     * 
     */
    readonly TaskType: number
    /**
     * 
     */
    readonly Text: string
    /**
     * 
     */
    readonly TaskCondition: number[]
    /**
     * 
     */
    readonly EndCondition: number[]
    /**
     * 
     */
    readonly AwardGroup: number
    /**
     * 
     */
    readonly AwardNum: number
    /**
     * 
     */
    readonly Jump: string

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
    }
}





export class TrVideo {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.ResPath = _buf_.ReadString()
        this.ResPathPhone = _buf_.ReadString()
        this.Desc = _buf_.ReadString()
        this.Pic = _buf_.ReadString()
        this.ResLocation = _buf_.ReadInt()
    }

    /**
     * ID
     */
    readonly Id: number
    /**
     * 
     */
    readonly ResPath: string
    /**
     * 
     */
    readonly ResPathPhone: string
    /**
     * 
     */
    readonly Desc: string
    /**
     * 
     */
    readonly Pic: string
    /**
     * 
     */
    readonly ResLocation: number

    resolve(tables:Tables) {
        
        
        
        
        
        
    }
}





export class TrVirtualTime {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Icon = _buf_.ReadString()
        this.Name = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.Time = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.Time.push(_e0);}}
        this.SpainPath = _buf_.ReadString()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.AnimationIdle = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.AnimationIdle.push(_e0);}}
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.AnimationRelax = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadString(); this.AnimationRelax.push(_e0);}}
    }

    /**
     * id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Icon: string
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly Time: number[]
    /**
     * spine
     */
    readonly SpainPath: string
    /**
     * 
     */
    readonly AnimationIdle: string[]
    /**
     * 
     */
    readonly AnimationRelax: string[]

    resolve(tables:Tables) {
        
        
        
        
        
        
        
    }
}





export class TrZhaoChaDragItem {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Stage = _buf_.ReadInt()
        this.Section = _buf_.ReadInt()
        { let n = Math.min(_buf_.ReadSize(), _buf_.Size); this.ItemId = []; for(let i = 0 ; i < n ; i++) { let _e0; _e0 = _buf_.ReadInt(); this.ItemId.push(_e0);}}
        this.InstanceId = _buf_.ReadInt()
        this.DragItemType = _buf_.ReadInt()
        this.Num = _buf_.ReadInt()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Stage: number
    /**
     * 
     */
    readonly Section: number
    /**
     * ID
     */
    readonly ItemId: number[]
    /**
     * Id
     */
    readonly InstanceId: number
    /**
     * 
     */
    readonly DragItemType: number
    /**
     * 
     */
    readonly Num: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
    }
}





export class TrZhaoChaItem {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Stage = _buf_.ReadInt()
        this.Section = _buf_.ReadInt()
        this.ItemId = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.Img = _buf_.ReadString()
        this.TalkText = _buf_.ReadString()
        this.TalkTime = _buf_.ReadInt()
        this.TalkDirection = _buf_.ReadInt()
        this.AnimationType = _buf_.ReadInt()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Stage: number
    /**
     * 
     */
    readonly Section: number
    /**
     * ID
     */
    readonly ItemId: number
    /**
     * 
     */
    readonly Name: string
    /**
     * 
     */
    readonly Img: string
    /**
     * 
     */
    readonly TalkText: string
    /**
     * 
     */
    readonly TalkTime: number
    /**
     * 
     */
    readonly TalkDirection: number
    /**
     * 
     */
    readonly AnimationType: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
    }
}





export class TrZhaoChaSection {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Stage = _buf_.ReadInt()
        this.SectionId = _buf_.ReadInt()
        this.LimitTime = _buf_.ReadInt()
        this.SectionPrefab = _buf_.ReadString()
        this.ShowMask = _buf_.ReadBool()
        this.Animation = new ZhaoCha.SectionAnimation(_buf_)
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Stage: number
    /**
     * Id
     */
    readonly SectionId: number
    /**
     * 
     */
    readonly LimitTime: number
    /**
     * 
     */
    readonly SectionPrefab: string
    /**
     *  Mask
     */
    readonly ShowMask: boolean
    readonly Animation: ZhaoCha.SectionAnimation

    resolve(tables:Tables) {
        
        
        
        
        
        
        this.Animation?.resolve(tables);
    }
}





export class TrZhaoChaStage {

    constructor(_buf_: ByteBuf) {
        this.Id = _buf_.ReadInt()
        this.Stage = _buf_.ReadInt()
        this.Name = _buf_.ReadString()
        this.Title = _buf_.ReadString()
        this.CoverImg = _buf_.ReadString()
        this.LimitTime = _buf_.ReadInt()
        this.FailAnim = _buf_.ReadString()
        this.WinAnim = _buf_.ReadString()
        this.ClickEffect = _buf_.ReadString()
        this.InvalidClick = _buf_.ReadInt()
        this.InvalidDrag = _buf_.ReadInt()
    }

    /**
     * Id
     */
    readonly Id: number
    /**
     * 
     */
    readonly Stage: number
    /**
     * 
     */
    readonly Name: string
    /**
     *  
     */
    readonly Title: string
    /**
     * 
     */
    readonly CoverImg: string
    /**
     * 
     */
    readonly LimitTime: number
    /**
     * 
     */
    readonly FailAnim: string
    /**
     * 
     */
    readonly WinAnim: string
    /**
     * 
     */
    readonly ClickEffect: string
    /**
     * 
     */
    readonly InvalidClick: number
    /**
     * 
     */
    readonly InvalidDrag: number

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
    }
}




export namespace ZhaoCha {
export class SectionAnimation {

    constructor(_buf_: ByteBuf) {
        this.Condition = _buf_.ReadInt()
        this.Arg1 = _buf_.ReadInt()
        this.Arg2 = _buf_.ReadInt()
        this.Prefab = _buf_.ReadString()
    }

    /**
     * 
     */
    readonly Condition: number
    /**
     * 1
     */
    readonly Arg1: number
    /**
     * 2
     */
    readonly Arg2: number
    /**
     * 
     */
    readonly Prefab: string

    resolve(tables:Tables) {
        
        
        
        
    }
}

}



export namespace DataTable {
export class TbItem {
    private _dataMap: Map<number, DataTable.Item>
    private _dataList: DataTable.Item[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, DataTable.Item>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: DataTable.Item
            _v = new DataTable.Item(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, DataTable.Item> { return this._dataMap; }
    getDataList(): DataTable.Item[] { return this._dataList; }

    get(key: number): DataTable.Item | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}
}



export class TbStrDictionary {
    private _dataMap: Map<string, TrStrDictionary>
    private _dataList: TrStrDictionary[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<string, TrStrDictionary>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrStrDictionary
            _v = new TrStrDictionary(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Key, _v)
        }
    }

    getDataMap(): Map<string, TrStrDictionary> { return this._dataMap; }
    getDataList(): TrStrDictionary[] { return this._dataList; }

    get(key: string): TrStrDictionary | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbTask {
    private _dataMap: Map<number, TrTask>
    private _dataList: TrTask[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrTask>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrTask
            _v = new TrTask(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrTask> { return this._dataMap; }
    getDataList(): TrTask[] { return this._dataList; }

    get(key: number): TrTask | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbPlayer {
    private _dataMap: Map<number, TrPlayer>
    private _dataList: TrPlayer[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrPlayer>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrPlayer
            _v = new TrPlayer(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrPlayer> { return this._dataMap; }
    getDataList(): TrPlayer[] { return this._dataList; }

    get(key: number): TrPlayer | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbConst {
    private _dataMap: Map<string, TrConst>
    private _dataList: TrConst[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<string, TrConst>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrConst
            _v = new TrConst(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Key, _v)
        }
    }

    getDataMap(): Map<string, TrConst> { return this._dataMap; }
    getDataList(): TrConst[] { return this._dataList; }

    get(key: string): TrConst | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbChat {
    private _dataMap: Map<number, TrChat>
    private _dataList: TrChat[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrChat>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrChat
            _v = new TrChat(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrChat> { return this._dataMap; }
    getDataList(): TrChat[] { return this._dataList; }

    get(key: number): TrChat | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbAtlas {
    private _dataMap: Map<string, TrAtlas>
    private _dataList: TrAtlas[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<string, TrAtlas>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrAtlas
            _v = new TrAtlas(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Key, _v)
        }
    }

    getDataMap(): Map<string, TrAtlas> { return this._dataMap; }
    getDataList(): TrAtlas[] { return this._dataList; }

    get(key: string): TrAtlas | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbVideo {
    private _dataMap: Map<number, TrVideo>
    private _dataList: TrVideo[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrVideo>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrVideo
            _v = new TrVideo(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrVideo> { return this._dataMap; }
    getDataList(): TrVideo[] { return this._dataList; }

    get(key: number): TrVideo | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class Tbreloading {
    private _dataMap: Map<number, Trreloading>
    private _dataList: Trreloading[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, Trreloading>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: Trreloading
            _v = new Trreloading(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, Trreloading> { return this._dataMap; }
    getDataList(): Trreloading[] { return this._dataList; }

    get(key: number): Trreloading | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbTalk {
    private _dataMap: Map<number, TrTalk>
    private _dataList: TrTalk[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrTalk>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrTalk
            _v = new TrTalk(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrTalk> { return this._dataMap; }
    getDataList(): TrTalk[] { return this._dataList; }

    get(key: number): TrTalk | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbAudio {
    private _dataMap: Map<number, TrAudio>
    private _dataList: TrAudio[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrAudio>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrAudio
            _v = new TrAudio(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrAudio> { return this._dataMap; }
    getDataList(): TrAudio[] { return this._dataList; }

    get(key: number): TrAudio | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbInteraction {
    private _dataMap: Map<number, TrInteraction>
    private _dataList: TrInteraction[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrInteraction>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrInteraction
            _v = new TrInteraction(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrInteraction> { return this._dataMap; }
    getDataList(): TrInteraction[] { return this._dataList; }

    get(key: number): TrInteraction | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbCondition {
    private _dataMap: Map<number, TrCondition>
    private _dataList: TrCondition[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrCondition>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrCondition
            _v = new TrCondition(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrCondition> { return this._dataMap; }
    getDataList(): TrCondition[] { return this._dataList; }

    get(key: number): TrCondition | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbEffect {
    private _dataMap: Map<number, TrEffect>
    private _dataList: TrEffect[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrEffect>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrEffect
            _v = new TrEffect(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrEffect> { return this._dataMap; }
    getDataList(): TrEffect[] { return this._dataList; }

    get(key: number): TrEffect | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbPlot {
    private _dataMap: Map<number, TrPlot>
    private _dataList: TrPlot[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrPlot>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrPlot
            _v = new TrPlot(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrPlot> { return this._dataMap; }
    getDataList(): TrPlot[] { return this._dataList; }

    get(key: number): TrPlot | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbChoice {
    private _dataMap: Map<number, TrChoice>
    private _dataList: TrChoice[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrChoice>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrChoice
            _v = new TrChoice(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrChoice> { return this._dataMap; }
    getDataList(): TrChoice[] { return this._dataList; }

    get(key: number): TrChoice | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbDate {
    private _dataMap: Map<number, TrDate>
    private _dataList: TrDate[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrDate>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrDate
            _v = new TrDate(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrDate> { return this._dataMap; }
    getDataList(): TrDate[] { return this._dataList; }

    get(key: number): TrDate | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbGuide {
    private _dataMap: Map<number, TrGuide>
    private _dataList: TrGuide[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrGuide>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrGuide
            _v = new TrGuide(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.GuideID, _v)
        }
    }

    getDataMap(): Map<number, TrGuide> { return this._dataMap; }
    getDataList(): TrGuide[] { return this._dataList; }

    get(key: number): TrGuide | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbSpecialEvent {
    private _dataMap: Map<number, TrSpecialEvent>
    private _dataList: TrSpecialEvent[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrSpecialEvent>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrSpecialEvent
            _v = new TrSpecialEvent(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrSpecialEvent> { return this._dataMap; }
    getDataList(): TrSpecialEvent[] { return this._dataList; }

    get(key: number): TrSpecialEvent | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbOpenFunction {
    private _dataMap: Map<number, TrOpenFunction>
    private _dataList: TrOpenFunction[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrOpenFunction>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrOpenFunction
            _v = new TrOpenFunction(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrOpenFunction> { return this._dataMap; }
    getDataList(): TrOpenFunction[] { return this._dataList; }

    get(key: number): TrOpenFunction | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbBook {
    private _dataMap: Map<number, TrBook>
    private _dataList: TrBook[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrBook>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrBook
            _v = new TrBook(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrBook> { return this._dataMap; }
    getDataList(): TrBook[] { return this._dataList; }

    get(key: number): TrBook | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbLevel {
    private _dataMap: Map<number, TrLevel>
    private _dataList: TrLevel[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrLevel>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrLevel
            _v = new TrLevel(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrLevel> { return this._dataMap; }
    getDataList(): TrLevel[] { return this._dataList; }

    get(key: number): TrLevel | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbHeroinePropType {
    private _dataMap: Map<number, TrHeroinePropType>
    private _dataList: TrHeroinePropType[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrHeroinePropType>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrHeroinePropType
            _v = new TrHeroinePropType(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrHeroinePropType> { return this._dataMap; }
    getDataList(): TrHeroinePropType[] { return this._dataList; }

    get(key: number): TrHeroinePropType | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbPropValue {
    private _dataMap: Map<number, TrPropValue>
    private _dataList: TrPropValue[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrPropValue>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrPropValue
            _v = new TrPropValue(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrPropValue> { return this._dataMap; }
    getDataList(): TrPropValue[] { return this._dataList; }

    get(key: number): TrPropValue | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbZhaoChaStage {
    private _dataMap: Map<number, TrZhaoChaStage>
    private _dataList: TrZhaoChaStage[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrZhaoChaStage>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrZhaoChaStage
            _v = new TrZhaoChaStage(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrZhaoChaStage> { return this._dataMap; }
    getDataList(): TrZhaoChaStage[] { return this._dataList; }

    get(key: number): TrZhaoChaStage | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbZhaoChaItem {
    private _dataMap: Map<number, TrZhaoChaItem>
    private _dataList: TrZhaoChaItem[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrZhaoChaItem>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrZhaoChaItem
            _v = new TrZhaoChaItem(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrZhaoChaItem> { return this._dataMap; }
    getDataList(): TrZhaoChaItem[] { return this._dataList; }

    get(key: number): TrZhaoChaItem | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbZhaoChaDragItem {
    private _dataMap: Map<number, TrZhaoChaDragItem>
    private _dataList: TrZhaoChaDragItem[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrZhaoChaDragItem>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrZhaoChaDragItem
            _v = new TrZhaoChaDragItem(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrZhaoChaDragItem> { return this._dataMap; }
    getDataList(): TrZhaoChaDragItem[] { return this._dataList; }

    get(key: number): TrZhaoChaDragItem | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbZhaoChaSection {
    private _dataMap: Map<number, TrZhaoChaSection>
    private _dataList: TrZhaoChaSection[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrZhaoChaSection>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrZhaoChaSection
            _v = new TrZhaoChaSection(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrZhaoChaSection> { return this._dataMap; }
    getDataList(): TrZhaoChaSection[] { return this._dataList; }

    get(key: number): TrZhaoChaSection | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbMagicBoxRandom {
    private _dataMap: Map<number, TrMagicBoxRandom>
    private _dataList: TrMagicBoxRandom[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrMagicBoxRandom>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrMagicBoxRandom
            _v = new TrMagicBoxRandom(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrMagicBoxRandom> { return this._dataMap; }
    getDataList(): TrMagicBoxRandom[] { return this._dataList; }

    get(key: number): TrMagicBoxRandom | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbBoyFriend {
    private _dataMap: Map<number, TrBoyFriend>
    private _dataList: TrBoyFriend[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrBoyFriend>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrBoyFriend
            _v = new TrBoyFriend(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrBoyFriend> { return this._dataMap; }
    getDataList(): TrBoyFriend[] { return this._dataList; }

    get(key: number): TrBoyFriend | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbBoyFriendLevel {
    private _dataMap: Map<number, TrBoyFriendLevel>
    private _dataList: TrBoyFriendLevel[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrBoyFriendLevel>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrBoyFriendLevel
            _v = new TrBoyFriendLevel(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrBoyFriendLevel> { return this._dataMap; }
    getDataList(): TrBoyFriendLevel[] { return this._dataList; }

    get(key: number): TrBoyFriendLevel | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbVirtualTime {
    private _dataMap: Map<number, TrVirtualTime>
    private _dataList: TrVirtualTime[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrVirtualTime>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrVirtualTime
            _v = new TrVirtualTime(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrVirtualTime> { return this._dataMap; }
    getDataList(): TrVirtualTime[] { return this._dataList; }

    get(key: number): TrVirtualTime | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbIdentity {
    private _dataMap: Map<number, TrIdentity>
    private _dataList: TrIdentity[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrIdentity>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrIdentity
            _v = new TrIdentity(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrIdentity> { return this._dataMap; }
    getDataList(): TrIdentity[] { return this._dataList; }

    get(key: number): TrIdentity | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbIdentityLevel {
    private _dataMap: Map<number, TrIdentityLevel>
    private _dataList: TrIdentityLevel[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrIdentityLevel>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrIdentityLevel
            _v = new TrIdentityLevel(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrIdentityLevel> { return this._dataMap; }
    getDataList(): TrIdentityLevel[] { return this._dataList; }

    get(key: number): TrIdentityLevel | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbAVGMap {
    private _dataMap: Map<number, TrAVGMap>
    private _dataList: TrAVGMap[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrAVGMap>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrAVGMap
            _v = new TrAVGMap(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrAVGMap> { return this._dataMap; }
    getDataList(): TrAVGMap[] { return this._dataList; }

    get(key: number): TrAVGMap | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbAVGSceneGroup {
    private _dataMap: Map<number, TrAVGSceneGroup>
    private _dataList: TrAVGSceneGroup[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrAVGSceneGroup>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrAVGSceneGroup
            _v = new TrAVGSceneGroup(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrAVGSceneGroup> { return this._dataMap; }
    getDataList(): TrAVGSceneGroup[] { return this._dataList; }

    get(key: number): TrAVGSceneGroup | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbAVGScene {
    private _dataMap: Map<number, TrAVGScene>
    private _dataList: TrAVGScene[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrAVGScene>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrAVGScene
            _v = new TrAVGScene(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrAVGScene> { return this._dataMap; }
    getDataList(): TrAVGScene[] { return this._dataList; }

    get(key: number): TrAVGScene | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbAVGNPC {
    private _dataMap: Map<number, TrAVGNPC>
    private _dataList: TrAVGNPC[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrAVGNPC>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrAVGNPC
            _v = new TrAVGNPC(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrAVGNPC> { return this._dataMap; }
    getDataList(): TrAVGNPC[] { return this._dataList; }

    get(key: number): TrAVGNPC | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbShopGift {
    private _dataMap: Map<number, TrShopGift>
    private _dataList: TrShopGift[]
    constructor(_buf_: ByteBuf) {
        this._dataMap = new Map<number, TrShopGift>()
        this._dataList = []
        for(let n = _buf_.ReadInt(); n > 0; n--) {
            let _v: TrShopGift
            _v = new TrShopGift(_buf_)
            this._dataList.push(_v)
            this._dataMap.set(_v.Id, _v)
        }
    }

    getDataMap(): Map<number, TrShopGift> { return this._dataMap; }
    getDataList(): TrShopGift[] { return this._dataList; }

    get(key: number): TrShopGift | undefined {
        return this._dataMap.get(key); 
    }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




type ByteBufLoader = (file: string) => ByteBuf

export class Tables {
    private _TbItem: DataTable.TbItem
    get TbItem(): DataTable.TbItem  { return this._TbItem;}
    private _TbStrDictionary: TbStrDictionary
    get TbStrDictionary(): TbStrDictionary  { return this._TbStrDictionary;}
    private _TbTask: TbTask
    get TbTask(): TbTask  { return this._TbTask;}
    private _TbPlayer: TbPlayer
    get TbPlayer(): TbPlayer  { return this._TbPlayer;}
    private _TbConst: TbConst
    get TbConst(): TbConst  { return this._TbConst;}
    private _TbChat: TbChat
    get TbChat(): TbChat  { return this._TbChat;}
    private _TbAtlas: TbAtlas
    get TbAtlas(): TbAtlas  { return this._TbAtlas;}
    private _TbVideo: TbVideo
    get TbVideo(): TbVideo  { return this._TbVideo;}
    private _Tbreloading: Tbreloading
    get Tbreloading(): Tbreloading  { return this._Tbreloading;}
    private _TbTalk: TbTalk
    get TbTalk(): TbTalk  { return this._TbTalk;}
    private _TbAudio: TbAudio
    get TbAudio(): TbAudio  { return this._TbAudio;}
    private _TbInteraction: TbInteraction
    get TbInteraction(): TbInteraction  { return this._TbInteraction;}
    private _TbCondition: TbCondition
    get TbCondition(): TbCondition  { return this._TbCondition;}
    private _TbEffect: TbEffect
    get TbEffect(): TbEffect  { return this._TbEffect;}
    private _TbPlot: TbPlot
    get TbPlot(): TbPlot  { return this._TbPlot;}
    private _TbChoice: TbChoice
    get TbChoice(): TbChoice  { return this._TbChoice;}
    private _TbDate: TbDate
    get TbDate(): TbDate  { return this._TbDate;}
    private _TbGuide: TbGuide
    get TbGuide(): TbGuide  { return this._TbGuide;}
    private _TbSpecialEvent: TbSpecialEvent
    get TbSpecialEvent(): TbSpecialEvent  { return this._TbSpecialEvent;}
    private _TbOpenFunction: TbOpenFunction
    get TbOpenFunction(): TbOpenFunction  { return this._TbOpenFunction;}
    private _TbBook: TbBook
    get TbBook(): TbBook  { return this._TbBook;}
    private _TbLevel: TbLevel
    get TbLevel(): TbLevel  { return this._TbLevel;}
    private _TbHeroinePropType: TbHeroinePropType
    get TbHeroinePropType(): TbHeroinePropType  { return this._TbHeroinePropType;}
    private _TbPropValue: TbPropValue
    get TbPropValue(): TbPropValue  { return this._TbPropValue;}
    private _TbZhaoChaStage: TbZhaoChaStage
    get TbZhaoChaStage(): TbZhaoChaStage  { return this._TbZhaoChaStage;}
    private _TbZhaoChaItem: TbZhaoChaItem
    get TbZhaoChaItem(): TbZhaoChaItem  { return this._TbZhaoChaItem;}
    private _TbZhaoChaDragItem: TbZhaoChaDragItem
    get TbZhaoChaDragItem(): TbZhaoChaDragItem  { return this._TbZhaoChaDragItem;}
    private _TbZhaoChaSection: TbZhaoChaSection
    get TbZhaoChaSection(): TbZhaoChaSection  { return this._TbZhaoChaSection;}
    private _TbMagicBoxRandom: TbMagicBoxRandom
    get TbMagicBoxRandom(): TbMagicBoxRandom  { return this._TbMagicBoxRandom;}
    private _TbBoyFriend: TbBoyFriend
    get TbBoyFriend(): TbBoyFriend  { return this._TbBoyFriend;}
    private _TbBoyFriendLevel: TbBoyFriendLevel
    get TbBoyFriendLevel(): TbBoyFriendLevel  { return this._TbBoyFriendLevel;}
    private _TbVirtualTime: TbVirtualTime
    get TbVirtualTime(): TbVirtualTime  { return this._TbVirtualTime;}
    private _TbIdentity: TbIdentity
    get TbIdentity(): TbIdentity  { return this._TbIdentity;}
    private _TbIdentityLevel: TbIdentityLevel
    get TbIdentityLevel(): TbIdentityLevel  { return this._TbIdentityLevel;}
    private _TbAVGMap: TbAVGMap
    get TbAVGMap(): TbAVGMap  { return this._TbAVGMap;}
    private _TbAVGSceneGroup: TbAVGSceneGroup
    get TbAVGSceneGroup(): TbAVGSceneGroup  { return this._TbAVGSceneGroup;}
    private _TbAVGScene: TbAVGScene
    get TbAVGScene(): TbAVGScene  { return this._TbAVGScene;}
    private _TbAVGNPC: TbAVGNPC
    get TbAVGNPC(): TbAVGNPC  { return this._TbAVGNPC;}
    private _TbShopGift: TbShopGift
    get TbShopGift(): TbShopGift  { return this._TbShopGift;}

    static getTableNames(): string[] {
        let names: string[] = [];
        names.push('datatable_tbitem');
        names.push('tbstrdictionary');
        names.push('tbtask');
        names.push('tbplayer');
        names.push('tbconst');
        names.push('tbchat');
        names.push('tbatlas');
        names.push('tbvideo');
        names.push('tbreloading');
        names.push('tbtalk');
        names.push('tbaudio');
        names.push('tbinteraction');
        names.push('tbcondition');
        names.push('tbeffect');
        names.push('tbplot');
        names.push('tbchoice');
        names.push('tbdate');
        names.push('tbguide');
        names.push('tbspecialevent');
        names.push('tbopenfunction');
        names.push('tbbook');
        names.push('tblevel');
        names.push('tbheroineproptype');
        names.push('tbpropvalue');
        names.push('tbzhaochastage');
        names.push('tbzhaochaitem');
        names.push('tbzhaochadragitem');
        names.push('tbzhaochasection');
        names.push('tbmagicboxrandom');
        names.push('tbboyfriend');
        names.push('tbboyfriendlevel');
        names.push('tbvirtualtime');
        names.push('tbidentity');
        names.push('tbidentitylevel');
        names.push('tbavgmap');
        names.push('tbavgscenegroup');
        names.push('tbavgscene');
        names.push('tbavgnpc');
        names.push('tbshopgift');
        return names;
    }

    constructor(loader: ByteBufLoader) {
        this._TbItem = new DataTable.TbItem(loader('datatable_tbitem'))
        this._TbStrDictionary = new TbStrDictionary(loader('tbstrdictionary'))
        this._TbTask = new TbTask(loader('tbtask'))
        this._TbPlayer = new TbPlayer(loader('tbplayer'))
        this._TbConst = new TbConst(loader('tbconst'))
        this._TbChat = new TbChat(loader('tbchat'))
        this._TbAtlas = new TbAtlas(loader('tbatlas'))
        this._TbVideo = new TbVideo(loader('tbvideo'))
        this._Tbreloading = new Tbreloading(loader('tbreloading'))
        this._TbTalk = new TbTalk(loader('tbtalk'))
        this._TbAudio = new TbAudio(loader('tbaudio'))
        this._TbInteraction = new TbInteraction(loader('tbinteraction'))
        this._TbCondition = new TbCondition(loader('tbcondition'))
        this._TbEffect = new TbEffect(loader('tbeffect'))
        this._TbPlot = new TbPlot(loader('tbplot'))
        this._TbChoice = new TbChoice(loader('tbchoice'))
        this._TbDate = new TbDate(loader('tbdate'))
        this._TbGuide = new TbGuide(loader('tbguide'))
        this._TbSpecialEvent = new TbSpecialEvent(loader('tbspecialevent'))
        this._TbOpenFunction = new TbOpenFunction(loader('tbopenfunction'))
        this._TbBook = new TbBook(loader('tbbook'))
        this._TbLevel = new TbLevel(loader('tblevel'))
        this._TbHeroinePropType = new TbHeroinePropType(loader('tbheroineproptype'))
        this._TbPropValue = new TbPropValue(loader('tbpropvalue'))
        this._TbZhaoChaStage = new TbZhaoChaStage(loader('tbzhaochastage'))
        this._TbZhaoChaItem = new TbZhaoChaItem(loader('tbzhaochaitem'))
        this._TbZhaoChaDragItem = new TbZhaoChaDragItem(loader('tbzhaochadragitem'))
        this._TbZhaoChaSection = new TbZhaoChaSection(loader('tbzhaochasection'))
        this._TbMagicBoxRandom = new TbMagicBoxRandom(loader('tbmagicboxrandom'))
        this._TbBoyFriend = new TbBoyFriend(loader('tbboyfriend'))
        this._TbBoyFriendLevel = new TbBoyFriendLevel(loader('tbboyfriendlevel'))
        this._TbVirtualTime = new TbVirtualTime(loader('tbvirtualtime'))
        this._TbIdentity = new TbIdentity(loader('tbidentity'))
        this._TbIdentityLevel = new TbIdentityLevel(loader('tbidentitylevel'))
        this._TbAVGMap = new TbAVGMap(loader('tbavgmap'))
        this._TbAVGSceneGroup = new TbAVGSceneGroup(loader('tbavgscenegroup'))
        this._TbAVGScene = new TbAVGScene(loader('tbavgscene'))
        this._TbAVGNPC = new TbAVGNPC(loader('tbavgnpc'))
        this._TbShopGift = new TbShopGift(loader('tbshopgift'))

        this._TbItem.resolve(this)
        this._TbStrDictionary.resolve(this)
        this._TbTask.resolve(this)
        this._TbPlayer.resolve(this)
        this._TbConst.resolve(this)
        this._TbChat.resolve(this)
        this._TbAtlas.resolve(this)
        this._TbVideo.resolve(this)
        this._Tbreloading.resolve(this)
        this._TbTalk.resolve(this)
        this._TbAudio.resolve(this)
        this._TbInteraction.resolve(this)
        this._TbCondition.resolve(this)
        this._TbEffect.resolve(this)
        this._TbPlot.resolve(this)
        this._TbChoice.resolve(this)
        this._TbDate.resolve(this)
        this._TbGuide.resolve(this)
        this._TbSpecialEvent.resolve(this)
        this._TbOpenFunction.resolve(this)
        this._TbBook.resolve(this)
        this._TbLevel.resolve(this)
        this._TbHeroinePropType.resolve(this)
        this._TbPropValue.resolve(this)
        this._TbZhaoChaStage.resolve(this)
        this._TbZhaoChaItem.resolve(this)
        this._TbZhaoChaDragItem.resolve(this)
        this._TbZhaoChaSection.resolve(this)
        this._TbMagicBoxRandom.resolve(this)
        this._TbBoyFriend.resolve(this)
        this._TbBoyFriendLevel.resolve(this)
        this._TbVirtualTime.resolve(this)
        this._TbIdentity.resolve(this)
        this._TbIdentityLevel.resolve(this)
        this._TbAVGMap.resolve(this)
        this._TbAVGSceneGroup.resolve(this)
        this._TbAVGScene.resolve(this)
        this._TbAVGNPC.resolve(this)
        this._TbShopGift.resolve(this)
    }
}

